export type { Movie } from './model/movieTypes'
export { MovieList } from './ui/MovieList/MovieList'
export { SearchMovies } from './ui/SearchMovies/SearchMovies'
export { NowPlayingMoviesList } from './ui/NowPlayingMoviesList/NowPlayingMoviesList'
export { useGetMovies } from './hooks/useGetMovies'
