export type { Movie, FullMovie, Genre, Actor } from './model/movieTypes'
export { MovieList } from './ui/MovieList/MovieList'
export { SearchMovies } from './ui/SearchMovies/SearchMovies'
export { MovieDetails } from './ui/MovieDetails/MovieDetails'
export { MoviesSlider } from './ui/MoviesSlider/MoviesSlider'
export { Catalog } from './ui/Catalog/Catalog'
export { NowPlayingMoviesList } from './ui/NowPlayingMoviesList/NowPlayingMoviesList'
export { useGetMovies } from './hooks/useGetMovies'
